### PR TITLE
tniASM support

### PR DESCRIPTION
**Pull request by theNestruo**
Adds tniASM (v0.x series) support: syntax highlight and problem matchers.
Main syntax differences are: some extra directives (IFEXIST) and relaxed whitespace constraints.

Also, adds a new snippet (MSX ROM cartridge header).

### CODE REVIEW

**Comment by mborik** [comment]
Hi, thanks for your contribution. Just one question: Why did you removed those positve lookbehind groups in some keyword matchers?

**Comment by theNestruo** [comment]
tniASM has a very relaxed whitespace constraints, so directives (and code) is not required to be preceeded by whitespace.
But maybe that's too lax for other assemblers; would be better to keep current groups and have separate ones specific for tniASM (without positive lookbehind, but only the tniASM directives)?
Thanks!

Also, I've just found this: https://github.com/mborik/z80-macroasm-vscode/pull/1#pullrequestreview-139288897, so I guess the MSX ROM cartridge header snippet should be removed.

**Comment by mborik** [comment]
Okay, well, so I will wait for these fixes and then I'll merge into master 😉

**Comment by theNestruo** [comment]
Thank you very much! :)

**Pull request merged**
